# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utjr0mycBs5c6Y0dsL4H5sgZblY5i9LS
"""

import numpy as np

"""RNNs"""

def one_hot(idx, size):
    vec = np.zeros((size,))
    vec[idx] = 1
    return vec

def softmax(x):
    exps = np.exp(x - np.max(x))
    return exps / np.sum(exps)

def prepare_data(text):
    vocab = list(set(text))
    word_to_idx = {w: i for i, w in enumerate(vocab)}
    idx_to_word = {i: w for w, i in word_to_idx.items()}
    return vocab, word_to_idx, idx_to_word

def init_model(vocab_size, embed_size=10, hidden_size=16):
    model = {
        "Wxh": np.random.randn(hidden_size, embed_size) * 0.01,
        "Whh": np.random.randn(hidden_size, hidden_size) * 0.01,
        "Why": np.random.randn(vocab_size, hidden_size) * 0.01,
        "bh": np.zeros((hidden_size,)),
        "by": np.zeros((vocab_size,)),
        "embedding": np.random.randn(vocab_size, embed_size) * 0.01,
        "hidden_size": hidden_size
    }
    return model

def forward(inputs, model, word_to_idx):
    Wxh, Whh, Why = model["Wxh"], model["Whh"], model["Why"]
    bh, by, embedding = model["bh"], model["by"], model["embedding"]
    hs = np.zeros((len(inputs) + 1, model["hidden_size"]))

    for t in range(len(inputs)):
        idx = word_to_idx[inputs[t]]
        x = embedding[idx]
        hs[t+1] = np.tanh(np.dot(Wxh, x) + np.dot(Whh, hs[t]) + bh)

    logits = np.dot(Why, hs[-1]) + by
    probs = softmax(logits)
    return probs, hs

def backward(inputs, target_idx, probs, hs, model, word_to_idx, learning_rate=0.01):
    Wxh, Whh, Why = model["Wxh"], model["Whh"], model["Why"]
    bh, by, embedding = model["bh"], model["by"], model["embedding"]

    dy = probs.copy()
    dy[target_idx] -= 1  # dL/dy

    dWhy = np.outer(dy, hs[-1])
    dby = dy.copy()

    dh = np.dot(Why.T, dy)
    dWxh = np.zeros_like(Wxh)
    dWhh = np.zeros_like(Whh)
    dbh = np.zeros_like(bh)
    dh_next = np.zeros_like(hs[0])

    for t in reversed(range(len(inputs))):
        temp = (1 - hs[t+1]**2) * (dh + dh_next)
        idx = word_to_idx[inputs[t]]
        x = embedding[idx]
        dWxh += np.outer(temp, x)
        dWhh += np.outer(temp, hs[t])
        dbh += temp
        dh_next = np.dot(Whh.T, temp)

    # Update weights
    model["Wxh"] -= learning_rate * dWxh
    model["Whh"] -= learning_rate * dWhh
    model["Why"] -= learning_rate * dWhy
    model["bh"] -= learning_rate * dbh
    model["by"] -= learning_rate * dby

def train(text, epochs=500, learning_rate=0.01):
    vocab, word_to_idx, idx_to_word = prepare_data(text)
    model = init_model(len(vocab))

    inputs = text[:-1]  # First 3 words
    target = text[-1]   # 4th word
    target_idx = word_to_idx[target]

    for epoch in range(epochs):
        probs, hs = forward(inputs, model, word_to_idx)
        loss = -np.log(probs[target_idx])
        backward(inputs, target_idx, probs, hs, model, word_to_idx, learning_rate)

        if epoch % 50== 0:
            pred_idx = np.argmax(probs)
            print(f"Epoch {epoch} | Loss: {loss:.4f} | Predicted: {idx_to_word[pred_idx]} | Target: {target}")

    return model, word_to_idx, idx_to_word

def predict(input_words, model, word_to_idx, idx_to_word):
    probs, _ = forward(input_words, model, word_to_idx)
    pred_idx = np.argmax(probs)
    return idx_to_word[pred_idx]

text = ["I", "love", "deep", "learning"]
model, word_to_idx, idx_to_word = train(text)

# Test prediction
test_input = ["I", "love", "deep"]
prediction = predict(test_input, model, word_to_idx, idx_to_word)
print("Final Prediction:", prediction)

